### PR TITLE
Add sqlite3support

### PR DESCRIPTION
**Pull request by Juules32**
Vi glemte tidligere at tilføje test .sql filer samt .sh script til at populate databasen. Det er fikset på denne branch, samt windows bat fil.

### CODE REVIEW

**Review by felaitu — CHANGES_REQUESTED** [review]
I'm not a huge fan of the structuring of the entire `scripts/`, and `data/` folder. Shouldn't they both be in the root of the project, instead of in `src/Chirp.Razor`? Also I'm not sure why there's suddenly not a leading `../` or `/` here: `var sqlDBFilePath = "tmp/chirp.db";` I can't seem to run this after cloning. Nice idea with a bat script, hadn't thought about that myself:)

**Comment by felaitu** [comment]
I put my recommended fixes [here](https://github.com/ITU-BDSA23-GROUP3/Chirp/tree/feat-addsqlite3support_2). Please feel free to review them and create an additional pull request. Otherwise you might be able to take some of what I added, and include in your revamped code:)

**Comment by Juules32** [comment]
i added your suggestions. using ";" after each command seems to fix the problem.

**Review by felaitu — APPROVED** [review]
Looks good to me!

**Pull request merged**
