### PR TITLE
Fixed deployments and added MS SQL server

### PR DESCRIPTION
**Pull request by AlbertRossJoh**

### CODE REVIEW

**Comment by Juules32** [comment]
commit 68c2d60 throws exception: "Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sqldatabase'. at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)"

commit f9e69e5 works though.

**Comment by AlbertRossJoh** [comment]
> commit 68c2d60 throws exception: "Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sqldatabase'. at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)"
> 
> 
> 
> commit f9e69e5 works though.

Could it be that you're not running it in development mode?

**Comment by Juules32** [comment]
No, that wasn't it - I am running in developer mode. if "Password=Adsa2023;" is added to the connectionstring, it works again.

I noticed the appsettings.Development.json file is not used anywhere in the code (as far as I can see). Could that have anything to do with the problem?

**Comment by AlbertRossJoh** [comment]
> No, that wasn't it - I am running in developer mode. if "Password=Adsa2023;" is added to the connectionstring, it works again.
> 
> 
> 
> I noticed the appsettings.Development.json file is not used anywhere in the code (as far as I can see). Could that have anything to do with the problem?

It should use the appsettings for the development mode automatically. I would not like to display a password to an sql server that is accessible publicly. Especially when I am paying for it😆.

**Review by NatalieClaraPetersen — APPROVED** [review]
I approve and believe we should merge and deploy ASAP

**Pull request merged**
